#!/usr/bin/env bash

changed_files="$(git diff-tree -r --name-only --no-commit-id ORIG_HEAD HEAD)"

check_run() {
  echo "$changed_files" | grep -E --quiet "$1" && eval "$2"
}

check_run composer.json "php ~/composer.phar self-update && php ~/composer.phar update"

php ~/composer.phar dump-autoload -o
php artisan optimize
php artisan migrate --pretend